### PR TITLE
Windows Group Policy template for Thunderbird

### PR DESCRIPTION
**Pull request by int-red**
As requested in https://bugzilla.mozilla.org/show_bug.cgi?id=1718603#c10
I made this pull request to bring the repo up-to date with the base repo  mozilla/policy-templates
and also added Windows Group Policy template for Thunderbird based on the most recent Firefox template.

### CODE REVIEW

**Comment by jobisoft** [comment]
Thanks! 

Do we need to include the firefox versions, if we declare this as the thunderbird templates repository (they seem to be identical to the ones currently available on https://github.com/mozilla/policy-templates)

The thunderbird files part of this PR, are they generated by the included powershell script or did you do any additional manual adjustments?

**Comment by int-red** [comment]
The Firefox templates are indeed identical to the ones currently available on https://github.com/mozilla/policy-templates)
but I thought the intention of your request for a pull request (https://bugzilla.mozilla.org/show_bug.cgi?id=1718603#c10) was to bring the Firefox templates up-to-date?

The thunderbird files are generated by the included powershell script. I did not change anything manually.
As I don't know which of the Firefox GPOs are actually implemented in Thunderbird, I didn't change anything.
The same goes for the definitions in which Thunderbird version a GPO actually was available the first time.

These thunderbird files are just a point to start from.
There is still a lot to do on them to make them 100% correct.
But at least there are thunderbird GPOs now and I think a lot of them will just work as they are.

About the merge conflict with "README.md" - the history says the current README.md is just the Firefox file where "Firefox" was replaced by "Thunderbird". So I guess it would be best to take the current README.md from my Pull request.

**Comment by jobisoft** [comment]
I have worked the past weeks on including the proper compatibility information. I am now pretty confident to have it right, the compatibility data is fully generated from source.

https://github.com/thundernest/policy-templates 

The main page is now directing the user to the proper template version, it also includes a list of all policies, to be able to see here directly, what we support and what not. Each policy description section also includes such a table.

* PLIST files (MacOS) and ADMX files (Windows) are adjusted (removed unsupported policies)
* All Readme  files are carefully checked if they include wrong information.

I still need to adjust the `supportedOn` values in the ADMX files.

I have moved your contributions to [templates/old](https://github.com/thundernest/policy-templates/tree/master/templates/old) and will remove it, when I am sure I did not mess this up. Thank you for giving me a kick-start to work on this. I would be happy, if you could have a look onto the new files and check if you see anything obviously wrong.

Thanks for your help,
John

**Comment by veasna33** [comment]
Hello,
I tested the parameter "PrimaryPassword": true, with Thunderbird 91.3.2 with policies.json through the folder distribution folder inside the thunderbird installation folder.
It didn't work .Even with the regedit parameter Software\Policies\Mozilla\Thunderbird\PrimaryPassword = 0x1 | 0x0
Other parameter like BlockAboutConfig":true, are working in policies.json
No problem with firefox "PrimaryPassword": true ask a master password to save new password.
Do you know if someone can test PrimaryPassword et fix that please ?
Thank you

**Comment by jobisoft** [comment]
Could you specify which version of Firefox you are using, where that works? I can confirm it does not work for us, but it also does not seem to work for Firefox 94.0.1?

What is the expected behavior when setting it to true or false?

**Comment by veasna33** [comment]
Hi,
I'm using Firefox 91.3.0esr
with PrimaryPassword set to 1 in \HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox
image
I can't disable the primary password
image
To enable it for the first time after the setting, you need to register a new password from any website.It will ask you to choose the primary password.
In thunderbird 91.3.2 it doesn't work with the same setting

**Pull request merged**
